services:
  - type: web
    name: playwright-scraper
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxss1 libxcomposite1 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libgtk-3-0 libxdamage1 libxfixes3 libx11-xcb1 libxext6
      npm install
    startCommand: |
      npx playwright install chromium
      node server.js
